# Generated by Django 3.2 on 2021-04-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('o', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mob_no',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
