# Generated by Django 3.2 on 2021-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210428_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/profiles/default.jpg', null=True, upload_to='profiles'),
        ),
    ]
