# Generated by Django 3.2 on 2021-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='isprimary',
            field=models.BooleanField(default=False),
        ),
    ]
