# Generated by Django 3.2 on 2021-05-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_isprimary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mob_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
