# Generated by Django 3.2 on 2021-05-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_mob_no'),
        ('accounts', '0007_auto_20210502_1948'),
    ]

    operations = [
    ]
