# Generated by Django 3.2 on 2021-05-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210509_1955'),
        ('accounts', '0009_auto_20210510_0904'),
    ]

    operations = [
    ]
