version: '2.15.1'

services:  

  db:
    image: postgres
    environment: 
      - POSTGRES_DB=eshopdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports: 
      - "5432:5432"
    restart: always

  eshop_gunicorn:
    volumes: 
      - static:/static
      - media:/media
    # env_file: 
    #   - .env
    build: 
      context: .
    ports: 
      - "8000:8000"
    depends_on:
     - db

  nginx:
    build: ./nginx
    volumes: 
      - static:/static
      - media:/media
    ports:
      - "80:80"
    depends_on:
      - eshop_gunicorn
      
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment: 
  #     - PGADMIN_DEFAULT_EMAIL=pg@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=1234
  #   ports: 
  #     - "5050:80"
  #   depends_on:
  #    - db

volumes:
  static:
  media: