# Generated by Django 3.0.5 on 2021-05-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210523_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
