# Generated by Django 3.0.5 on 2021-05-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210502_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articel_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender_cat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_cat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
