# Generated by Django 3.0.5 on 2021-05-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210523_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagesurl',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
