# Generated by Django 3.0.5 on 2021-05-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210503_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
    ]
