# Generated by Django 3.0.5 on 2021-05-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_accounts', '0002_auto_20210502_1948'),
        ('cart', '0004_auto_20210503_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller_accounts.CompanyDetails'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
