# Generated by Django 3.2 on 2021-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mob_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
