# Generated by Django 3.2 on 2021-05-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_mob_no'),
        ('cart', '0007_auto_20210505_2012'),
    ]

    operations = [
    ]
