# Generated by Django 3.2 on 2021-05-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20210510_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
