# Generated by Django 3.2 on 2021-05-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_sales_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sales',
        ),
    ]
