# Generated by Django 3.2 on 2021-05-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210509_1955'),
        ('cart', '0013_remove_order_sales'),
    ]

    operations = [
    ]
