# Generated by Django 3.2 on 2021-05-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20210510_0924'),
        ('seller_accounts', '0003_auto_20210510_0904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
