# Generated by Django 3.2 on 2021-05-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_accounts', '0003_auto_20210509_1955'),
        ('seller_accounts', '0004_delete_sales'),
    ]

    operations = [
    ]
