# Generated by Django 3.2 on 2021-05-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customerqueries'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerqueries',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customerqueries',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerqueries',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
